name: vce-guide-builder
#.github/workflows/nbval.yml
on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: Module
        options: 
        - "m348"
        - "tm351"
        - "tm129"
        - "default"
jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: outm351dev/ou-doc-builder
    steps:
    # https://github.com/myoung34/docker-github-actions-runner/issues/261
    - uses: actions/checkout@v1
    - name: Build documentation
      run: |
        ./build_pdf_docx.sh ${{ github.event.inputs.module }}
        mkdir -p /var/tmp/dist
        cp -rf _build/html /var/tmp/dist/
        cp -rf _build/ouxml /var/tmp/dist/
        cp _build/latex/book.pdf /var/tmp/dist/${{github.event.inputs.module}}.pdf
        cp buildpack/${{github.event.inputs.module}}/_generated/${{github.event.inputs.module}}_cribsheet.pdf /var/tmp/dist/
    - name: Upload docs bundle
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.event.inputs.module}}_docs_bundle
        path: /var/tmp/dist